// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { normalizePgConnectionString } from "./lib/pg-connection-url";

const rawUrl = process.env["DATABASE_URL"];
const datasourceUrl = rawUrl ? normalizePgConnectionString(rawUrl) : rawUrl;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: datasourceUrl,
  },
});
